
runtime: python27
threadsafe: yes
api_version: 1

# MUST BE IN FORMAT MAJOR.MINOR
# NO LONGER UNDER DEVELOPMENT ONCE MAJOR >= 1
env_variables:
  WEBSITE_VERSION: '0.1'

handlers:

- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico

- url: /assets/app.manifest
  static_files: assets/app.manifest
  mime_type: text/cache-manifest
  upload: assets/app.manifest
  expiration: '0'

- url: /assets
  static_dir: assets
  # expiration: '30d'

- url: /lib
  static_dir: lib
  expiration: '30d'

- url: /
  script: main.application
  secure: always
  redirect_http_response_code: 301
  # login: admin

- url: .*
  script: main.application
  # login: admin

# - url: /cron/job
#   script: reports.app
#   login: admin (prevents people from getting to page)
